//resource
//Widget
//{
//name "black_bkg"
//rect 0 0 640 480
//fgcolor 1.00 1.00 1.00 1.00
//bgcolor 0.00 0.00 0.00 0.50
//borderstyle "none"
//ordernumber 1
//}

resource
Widget
{
name "dlg_bkg-01"
rect 160 120 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "none"
ordernumber 1
shader menu/dlg/bkg_01
}

resource
Widget
{
name "dlg_bkg-02"
rect 416 120 64 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "none"
ordernumber 1
shader menu/dlg/bkg_02
}

resource
widget
{
	rect 	 206 285 256 32
	fgcolor 1.00 1.00 0.00 1.00
	bgcolor 0.00 0.00 0.00 0.00
	borderstyle "none"
	
	shader menu/main/credits
	
	shadercolor 0.700 0.800 1.00 1.00
	hovershadercolor 0.700 0.800 1.00 1.00
	armedshadercolor 0.700 0.800 1.00 1.00
	selectedshadercolor 0.700 0.800 1.00 1.00
}

end.