resource
Widget
{
name "mp_bkg_01"
rect 0 87 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 1.00 1.00 1.00 0.00
borderstyle "none"
ordernumber 1
shader menu/mp/bkg_01
}

resource
Widget
{
name "mp_bkg_02"
rect 256 87 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 1.00 1.00 1.00 0.00
borderstyle "none"
ordernumber 1
shader menu/mp/bkg_02
}

resource
Widget
{
name "mp_bkg_03"
rect 512 87 128 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 1.00 1.00 1.00 0.00
borderstyle "none"
ordernumber 1
shader menu/mp/bkg_03
}

resource
Widget
{
name "mp_bkg_04"
rect 0 343 256 128
fgcolor 1.00 1.00 1.00 1.00
bgcolor 1.00 1.00 1.00 0.00
borderstyle "none"
ordernumber 1
shader menu/mp/bkg_04
}

resource
Widget
{
name "mp_bkg_05"
rect 256 343 256 128
fgcolor 1.00 1.00 1.00 1.00
bgcolor 1.00 1.00 1.00 0.00
borderstyle "none"
ordernumber 1
shader menu/mp/bkg_05
}

resource
Widget
{
name "mp_bkg_06"
rect 512 343 128 128
fgcolor 1.00 1.00 1.00 1.00
bgcolor 1.00 1.00 1.00 0.00
borderstyle "none"
ordernumber 1
shader menu/mp/bkg_06
}

end.